// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todos.proto

package todorpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=Completed,proto3" json:"Completed,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703e18c08e8710, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Todo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *Todo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type TodoRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoRequest) Reset()         { *m = TodoRequest{} }
func (m *TodoRequest) String() string { return proto.CompactTextString(m) }
func (*TodoRequest) ProtoMessage()    {}
func (*TodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703e18c08e8710, []int{1}
}

func (m *TodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoRequest.Unmarshal(m, b)
}
func (m *TodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoRequest.Marshal(b, m, deterministic)
}
func (m *TodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoRequest.Merge(m, src)
}
func (m *TodoRequest) XXX_Size() int {
	return xxx_messageInfo_TodoRequest.Size(m)
}
func (m *TodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoRequest proto.InternalMessageInfo

func (m *TodoRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type TodoResponse struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703e18c08e8710, []int{2}
}

func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (m *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(m, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type TodosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodosRequest) Reset()         { *m = TodosRequest{} }
func (m *TodosRequest) String() string { return proto.CompactTextString(m) }
func (*TodosRequest) ProtoMessage()    {}
func (*TodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703e18c08e8710, []int{3}
}

func (m *TodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodosRequest.Unmarshal(m, b)
}
func (m *TodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodosRequest.Marshal(b, m, deterministic)
}
func (m *TodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodosRequest.Merge(m, src)
}
func (m *TodosRequest) XXX_Size() int {
	return xxx_messageInfo_TodosRequest.Size(m)
}
func (m *TodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodosRequest proto.InternalMessageInfo

type TodosResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodosResponse) Reset()         { *m = TodosResponse{} }
func (m *TodosResponse) String() string { return proto.CompactTextString(m) }
func (*TodosResponse) ProtoMessage()    {}
func (*TodosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7703e18c08e8710, []int{4}
}

func (m *TodosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodosResponse.Unmarshal(m, b)
}
func (m *TodosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodosResponse.Marshal(b, m, deterministic)
}
func (m *TodosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodosResponse.Merge(m, src)
}
func (m *TodosResponse) XXX_Size() int {
	return xxx_messageInfo_TodosResponse.Size(m)
}
func (m *TodosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodosResponse proto.InternalMessageInfo

func (m *TodosResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func init() {
	proto.RegisterType((*Todo)(nil), "todorpc.Todo")
	proto.RegisterType((*TodoRequest)(nil), "todorpc.TodoRequest")
	proto.RegisterType((*TodoResponse)(nil), "todorpc.TodoResponse")
	proto.RegisterType((*TodosRequest)(nil), "todorpc.TodosRequest")
	proto.RegisterType((*TodosResponse)(nil), "todorpc.TodosResponse")
}

func init() { proto.RegisterFile("todos.proto", fileDescriptor_a7703e18c08e8710) }

var fileDescriptor_a7703e18c08e8710 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0x4f, 0xc9,
	0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x71, 0x8a, 0x0a, 0x92, 0x95, 0xd2,
	0xb8, 0x58, 0x42, 0xf2, 0x53, 0xf2, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x98, 0x3c, 0x5d, 0x84, 0x84, 0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98,
	0xc0, 0x22, 0x60, 0xb6, 0x90, 0x0c, 0x17, 0xa7, 0x73, 0x7e, 0x6e, 0x41, 0x4e, 0x6a, 0x49, 0x6a,
	0x8a, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x42, 0x00, 0x2c, 0x5b, 0x94, 0x9a, 0x58, 0x92,
	0x9a, 0xe2, 0x58, 0x22, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x10, 0x50, 0x92, 0xe5, 0xe2,
	0x06, 0xd9, 0x13, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x82, 0x6e, 0x9d, 0x92, 0x21, 0x17, 0x0f,
	0x44, 0xba, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x91, 0x8b, 0x05, 0xe4, 0x42, 0xb0, 0x0a,
	0x6e, 0x23, 0x5e, 0x3d, 0xa8, 0x73, 0xf5, 0xc0, 0x8a, 0xc0, 0x52, 0x4a, 0x7c, 0x10, 0x2d, 0xc5,
	0x50, 0x23, 0x95, 0x4c, 0xb8, 0x78, 0xa1, 0x7c, 0xa8, 0x19, 0xca, 0x5c, 0xac, 0x60, 0x2f, 0x4b,
	0x30, 0x2a, 0x30, 0x63, 0x1a, 0x02, 0x91, 0x4b, 0x62, 0x03, 0x87, 0x87, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xe2, 0xd2, 0x44, 0x96, 0x1e, 0x01, 0x00, 0x00,
}
